# Configuracion de Base de Datos MySQL
db.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=SGDpqc;encrypt=false;trustServerCertificate=true;loginTimeout=30
db.user=PQCusu
db.password=PQCusu456

# Configuracion de Tablas
db.table.name=IDOSGD.TDTV_ARCHIVO_DOC
db.column.id=BL_DOC
db.column.pdf=pdf_blob

# Configuracion de Keystore PQC
keystore.path=pqc_keystore.p12
keystore.password=changeit
keystore.alias=pqc-key
